# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  ###############
  # Looping through (1..3) for
  # creating 3 worker nodes
  ###############

  (1..2).each do |i|
      config.vm.define "worker-#{i}" do |node|
        # Every Vagrant development environment requires a box. You can search for
        # boxes at https://vagrantcloud.com/search.
        node.vm.box = "bento/ubuntu-24.04"
        node.vm.box_version = "202502.21.0"
        node.vm.hostname = "k8s-worker-#{i}"

        # Disable automatic box update checking. If you disable this, then
        # boxes will only be checked for updates when the user runs
        # `vagrant box outdated`. This is not recommended.
        # config.vm.box_check_update = false

        # Configuring disk to utilize for stateful sets
        node.vm.disk :disk, name: "worker-disk-#{i}", size: "10GB"

        # configuring vbguest additions
        node.vbguest.auto_update = false
        # node.vbguest.iso_path = "../VBoxGuestAdditions.iso"

        # Create a forwarded port mapping which allows access to a specific port
        # within the machine from a port on the host machine. In the example below,
        # accessing "localhost:8080" will access port 80 on the guest machine.
        # NOTE: This will enable public access to the opened port
        # config.vm.network "forwarded_port", guest: 80, host: 8080

        # Create a forwarded port mapping which allows access to a specific port
        # within the machine from a port on the host machine and only allow access
        # via 127.0.0.1 to disable public access
        # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

        # Create a private network, which allows host-only access to the machine
        # using a specific IP.
        node.vm.network "private_network", ip: "192.168.60.2#{i}"

        # Create a public network, which generally matched to bridged network.
        # Bridged networks make the machine appear as another physical device on
        # your network.
        # config.vm.network "public_network"

        # Share an additional folder to the guest VM. The first argument is
        # the path on the host to the actual folder. The second argument is
        # the path on the guest to mount the folder. And the optional third
        # argument is a set of non-required options.
        node.vm.synced_folder "../data/worker-#{i}", "/host_data"
        node.vm.synced_folder "../data/shared", "/shared_data"

        # Disable the default share of the current code directory. Doing this
        # provides improved isolation between the vagrant box and your host
        # by making sure your Vagrantfile isn't accessible to the vagrant box.
        # If you use this you may want to enable additional shared subfolders as
        # shown above.
        # config.vm.synced_folder ".", "/vagrant", disabled: true

        # Provider-specific configuration so you can fine-tune various
        # backing providers for Vagrant. These expose provider-specific options.
        # Example for VirtualBox:
        #
        node.vm.provider "virtualbox" do |vb|
            # Display the VirtualBox GUI when booting the machine
            vb.gui = false
            vb.name = "worker-#{i}"

            # Customize the amount of memory on the VM:
            vb.memory = "2048"
            vb.cpus = 2
        end

        #
        # View the documentation for the provider you are using for more
        # information on available options.

        # Enable provisioning with a shell script. Additional provisioners such as
        # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
        # documentation for more information about their specific syntax and use.

        # preparing node for the kubernetes
        node.vm.provision "shell", path: "../k8s_node.sh"

        # VirtualBox NAT will add same ip to all VMs, causing network problems
        # solution: Configuring kubelet with NODE IP.
        # Kubelet systemd service will read overwrites from /etc/default/kubelet
        node.vm.provision "shell", inline: <<-SCRIPT
        sudo echo "KUBELET_EXTRA_ARGS='--node-ip=192.168.60.2#{i}'" > /etc/default/kubelet
        sudo systemctl restart kubelet
        SCRIPT

        # configure the node for openebs storage
        # uncomment following line for openebs storage
        node.vm.provision "shell", path: "openebs-node.sh"

        # run kubeadm to join the cluster
        node.vm.provision "shell", path: "worker.sh"
      end
  end
end
